name: Trigger auto deployment for container-app-icrznzugq3k2i

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-icrznzugq3k2i-AutoDeployTrigger-e7e80244-2895-435d-b4ae-56c01e582409.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPICRZNZUGQ3K2I_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPICRZNZUGQ3K2I_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPICRZNZUGQ3K2I_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPICRZNZUGQ3K2I_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPICRZNZUGQ3K2I_REGISTRY_PASSWORD }}
          containerAppName: container-app-icrznzugq3k2i
          resourceGroup: djangoappspacesbfe0872d
          imageToBuild: default/container-app-icrznzugq3k2i:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


